---
title: "2023-7-27-blog-post-5"
author: "Demetrios Samaras"
date: "2023-07-27"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE)
```


## What your current thoughts are in terms of using R for data science - do you think you'll continue to use R going forward?  Why or why not

I think that R is an incredibly useful and powerful tool for doing data science and analysis. I think I will continue to use R going forward one way or another. I think if I have any problems that I can use it to help solve that would be great, but even if I don’t I think I will still try to play around with it from time to time because I have grown to enjoy it.

## What things are you going to do differently in practice now that you've had this course

I think the main thing that this course has done as part of teaching me a language is to also give me a different mindset and to have a different approach to problem solving. I think the main thing that I will do differently in practice is change the way that I approach problems and think about how to solve them using coding. 

## What areas of statistics/data science are you thinking about exploring further?

I think that contacting and pulling data from API’s seems like a powerful tool and something that can be used for several interesting problems so I would like to explore that further. I also found the supervised learning models that we used very interesting, but I feel like we just scratched the surface and I would like to gain more depth of understanding for those topics. 

