---
title: "2023-7-9-ST558-project-2-post"
author: "Demetrios Samaras"
date: "2023-07-09"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE)
```

Once you’ve completed the project each of you should write a brief blog post outlining your project and two links to the username.github.io/repo-name site and the repo itself (the username may correspond to your partner). You should then also reflect on the process you went through. Discuss the following:
links: 

repo (https://github.com/kgolden4514/ST_558_Project_2)[https://github.com/kgolden4514/ST_558_Project_2]

pages (https://kgolden4514.github.io/Tech.html)[https://kgolden4514.github.io/Tech.html]
(https://kgolden4514.github.io/World.html)[https://kgolden4514.github.io/World.html]
(https://kgolden4514.github.io/Social.Media.html)[https://kgolden4514.github.io/Social.Media.html]
(https://kgolden4514.github.io/Lifestyle.html)[https://kgolden4514.github.io/Lifestyle.html]
(https://kgolden4514.github.io/Entertainment.html)[https://kgolden4514.github.io/Entertainment.html]
(https://kgolden4514.github.io/Business.html)[https://kgolden4514.github.io/Business.html]

what would you do differently?

The main thing that I would do differently is try to make sure that the random forest was always cached and only use a single mtry because the random forest takes forever to run. I would also have the repo/pages setup sooner because even though our project was basically done we ran into some issues getting the rendered documents to show graphs and having the pages show up properly on the due date. 

what was the most difficult part for you?

The most difficult part for me was trying to figure out why the automated renders would work with html and not show images with .md. the problem ended up being that you couldn't specify output_dir because it would mess up the way github links the figures, but it took me 4 hours to figure that out.  another difficult part was also the proper range of tuning parameters for the boosted tree models because for this data set it seemed to depend heavily on the data Chanel and did not seem to follow the trend of more=better that we saw in the notes. 

what are your big take-aways from this project?

I think the biggest takeaway for me was that this data set seems to have a lot of noise and getting good predictive models for this type of data is hard and requires a lot of fine tuning. And also that random forests take forever. 